### ISSUE TITLE
Weather App not Rendering

### ISSUE THREAD

**Issue by edescamps** [ericwindmill/flutter_in_action#1]
When rendering the weather app example, I came into a "Bad state: No element" error. This was due to a parameter being passed into Forecast.getSelectedDayForecast inside of ForecastController. The issue was fixed by passing in the date using _today, declared and assigned a few lines above.

ORIGINALLY:

    ForecastController(City this.city) {
        var helper = new WeatherDataHelper();
        forecast = helper.generateTenDayForecast(city);
        selectedDay = Forecast.getSelectedDayForecast(
            forecast, DateTime(_today.year, _today.month, _today.day));
    
        selectedHourlyTemperature = ForecastDay.getHourSelection(
            selectedDay, DateTime.now().toLocal().hour);
      }

FIX:

    ForecastController(City this.city) {
        var helper = new WeatherDataHelper();
        forecast = helper.generateTenDayForecast(city);
        selectedDay = Forecast.getSelectedDayForecast(
            forecast, _today);
    
        selectedHourlyTemperature = ForecastDay.getHourSelection(
            selectedDay, DateTime.now().toLocal().hour);
      }

**Comment by ericwindmill** [comment]
Fixed, thank you!
